version: "3.9"

services:
  app:
    build: .
    container_name: swagly-app
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - swagly-network

  nginx:
    image: nginx:latest
    container_name: swagly-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/html
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - app
    networks:
      - swagly-network

networks:
  swagly-network:
